// This file is autogenerated by Redwood and will be overwitten periodically

import { db } from 'src/lib/db'
import datamodel from '../../../.redwood/datamodel.json'
import { RedwoodRecord } from '@redwoodjs/record'

RedwoodRecord.db = db
RedwoodRecord.schema = datamodel

import Contact from 'src/models/Contact'

Contact.requiredModels = []

export { Contact }
